### ISSUE TITLE
PdfPig throws "Index was out of range" in Getpage()

### ISSUE THREAD

**Issue by fviollette** [UglyToad/PdfPig#355]
Hi, 

I have an exception while reading some pdf with GetPages(). 
Occurs on 0.1.5-alpha002. 

Error message : 
`"Index was out of range. Must be non-negative and less than the size of the collection parameter name:index"`

This error occurs in this line of ReflectionGraphicsStateOperationFactory.cs when  `IReadOnlyList<IToken> operands` is empty.   https://github.com/UglyToad/PdfPig/blob/72db3bf244953b576a0ce75356f034e18c6cd64d/src/UglyToad.PdfPig/Graphics/ReflectionGraphicsStateOperationFactory.cs#L276

Unfortunatly, due to the sensitive content of these pdf I cannot attached it.
Are there some informations about it that could help you to investiguate (version, metadatas, ...) ? 

Have you ever facing a similar issue ? 

Thanks in advance, 

Florent

**Comment by EliotJones** [comment]
Hi @fviollette I've pushed a potential fix to this but I don't think it fixes the underlying issue, do these files open correctly with e.g. Adobe Reader? If this fix works they're very incompatible with the specification.

**Comment by fviollette** [comment]
Hi @EliotJones, 
Thanks for your fix. I will test it today. 
And I can confirm that these files can be opened correctly with Adobe Reader.

**Comment by fviollette** [comment]
@EliotJones, I am still facing two issues even with your changes. 
In ReflectionGraphicsStateOperationFactory.cs : 

In my case, I have two operands here... 
```
case ShowText.Symbol:
        if (operands.Count != 1)
        {
                throw new InvalidOperationException($"Attempted to create a show text operation with {operands.Count} operands.");
        }
```
If I return null instead of throwing an exception I looks okay untif this next error here : 
```
                case SetFontAndSize.Symbol:
                    return new SetFontAndSize((NameToken)operands[0], OperandToDecimal(operands[1]));
```
I made this small changes and it works fine. 

```
                case SetFontAndSize.Symbol:
                    if (operands.Count == 3 && OperandToDecimal(operands[0]) == 0)
                    {
                        return new SetFontAndSize((NameToken)operands[1], OperandToDecimal(operands[2]));
                    }
                    return new SetFontAndSize((NameToken)operands[0], OperandToDecimal(operands[1]));
```
Indeed, here sometimes I have an emty numericToken as first element in my operands. Sadly, I don't know why... 

Have you ever found issue like these ? Do you think my changes could be a workable solution ?

**Comment by fviollette** [comment]
@EliotJones I think we have found the issue with my pdf. 
ReflectionGraphicsStateOperationFactory throw in some step when I have a wrong number of operands. 
In my previous post, 2 operands instead of 1 in my first example and 3 instead of 2 in the second. 

So, the issue in not how to deal with them but why there are extra operands? 
And I think we found the answer. 

Below, a part of my decoded pdf. I have similar things in every pages. 
```
...
0.00 --21.72 TD
/F1 8.00 Tf
(Accidents du travail - maladies professionnelles) Tj
0.00 --21.76 TD
(Retraite) Tj
0.00 --10.48 TD
/F0 8.00 Tf
(S?curit? sociale plafonn?e) Tj
0.00 --10.52 TD
(S?curit? sociale d?plafonn?e) Tj
0.00 --10.48 TD
(Compl?mentaire tranche a) Tj
0.00 --10.48 TD
(Compl?mentaire tranche b) Tj
0.00 --10.52 TD
(Compl?mentaire cet) Tj
0.00 --21.72 TD
/F1 8.00 Tf
...
```

After some investiguation, we conclude that each time we have an extra operand, it came from the previous line. In my debugger, we found that in the above example, we have 0.00 as extra operand in each following "Tj" or "Tf" symbol. 

We think that in this method of the coreScannerToken class https://github.com/UglyToad/PdfPig/blob/a3e316958abd40dfb48cf088b9018d513e665d24/src/UglyToad.PdfPig.Tokenization/Scanner/CoreTokenScanner.cs#L81
we failed to interpret correctly these chars: --10.48 and in particular the **--** part. 
As a result, we skip this symbol (line) but it looks like we keep the first part (0.00) and postponed it to the next line. That's why we get an extra operand. 

May be we should skip the whole line if there is an issue to interpret something on it and we should be able to interpret --10.48 as a correct numerictoken, Adobe or chrome interpret it correctly. 

What do you think about this explanation ? And how to fix it correctly ?

**Comment by EliotJones** [comment]
@fviollette thanks that looks like the exact problem, I will fix numeric tokenizer to treat `--` as a single negative number (I'm presuming that's the correct value and it's not `-(-10)`, e.g. `+10`)

**Comment by fviollette** [comment]
@EliotJones I think the fact that the operand 0.00 were postponed on the other symbol is also an issue that should be fix. Because this operand without the correct symbol is useless. 
Another question, when do you think you will be able to release this ?

**Comment by fviollette** [comment]
@EliotJones I made some test and I confirm that your commit fix my issue. 
Thanks ! 
When do you plan to release this as a third Alpha ?
