### ISSUE TITLE
Letter width/font is incorrect

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#41]
Hi, I'm trying to extract text letters and positions from PDFs. For most documents it's working great, but for attached sample (and many others) it's returning Letter.Width=0 and Letter.FontSize=1
Any ideas how to work around this? Thank you!
[letter_size_problem.pdf](https://github.com/UglyToad/PdfPig/files/3327341/letter_size_problem.pdf)

```
            using (PdfDocument document = PdfDocument.Open(@"letter_size_problem.pdf"))
            {
                var page = document.GetPage(1);

                Letter l = page.Letters[0];

                decimal x = l.Location.X;
                decimal y = l.Location.Y;
                decimal width = l.Width;
                decimal fontSize = l.FontSize;
            }

```

**Comment by EliotJones** [comment]
Hi, sorry for the long wait. I've pushed up some changes that address both page rotation and, as a result, the letter width. However this leads to letter coordinates becoming negative. I've attached an image which hopefully makes the reason for this clearer:

![image](https://user-images.githubusercontent.com/7862346/60756912-7d576d00-9ffb-11e9-82fd-f2fdc2ace027.png)

When the page is rotated through 90 degrees clockwise the origin becomes based at the top left of the page so while letter x coordinates remain positive, the y coordinates are negative because the top of the page is now at zero.

Please give this change a try on the documents you were having problems with and let me know how you get on, thanks.

**Comment by vadik299** [comment]
Eliot, thank you very much! The coordinates and width seem OK now. Negative values make sense, since you added "Rotation" property.

One issue still remains - FontSize for this PDF is returned as "1" for all glyphs. Can it be fixed or is there another way to get the font size? I thought I could use GlyphRectangle.Height, but it's different for every letter in the same word, and it makes it hard to merge letters later on.

**Comment by EliotJones** [comment]
Letter size is unfortunately complicated in PDF documents. I'm still not sure I understand it myself. The exposed member on the `Letter` class `Letter.FontSize` is based on the size operator in the content stream before the letter undergoes transforms using several other matrices.

There is an `internal` property, `PointSize`, on `Letter` which attempts to map back to 'normal' font sizes as we'd understand them. I've changed the calculation of this value to be, hopefully, closer to the correct value. I'm not making the property `public` for now because I think it's still almost certainly wrong.

I've added a way to retrieve this value through the `ExperimentalAccess` member of the `Page` class to avoid the need for reflection. For example:

```
var page = document.GetPage(1);
var letter = page.Letters[0];
decimal size = page.ExperimentalAccess.GetPointSize(letter);
```

Hopefully in future someone who is better at understanding the various matrix transforms required than me will fix the calculation and the value for point sizes will change, so they should only be relied on for being consistent in the same version.

For anyone interested there's a better explanation of the problem in this StackOverflow answer: https://stackoverflow.com/questions/48010235/pdf-specification-get-font-size-in-points

Please have a go with this new `GetPointSize` method and let me know if it works for your documents, thanks.

**Comment by vadik299** [comment]
This works!

I used both, like this:
if (letter.FontSize==1) size=page.ExperimentalAccess.GetPointSize(letter); else size = letter.FontSize;

I will test with more documents, but a few that had this problem seem to work very well now.
Thank you!
