### ISSUE TITLE
Letter bounding boxes with no height and issue with location on this document

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#78]
When drawing bounding boxes for letters and images on [this document](https://pdfs.semanticscholar.org/70ae/5b583303af0b4d60d356d08f8ed84e1babbc.pdf), some don't have Height (Height=0) and the location appears to be incorrect (for both letters and images).

The issue on location might come from what are considered to be the Height and Width for the bitmap (bitmap.Height = 699 and bitmap.Width = 550) and the page data:
- page.CropBox.Bounds = {[(x:40, y:761), 550, 699]}
- page.Height = 792
- page.Width = 612

I think the location of the bounding box does not take in account the page's CropBox.Bounds.

See below example with page 9 (letters in pink, images in green):
![New Algorithm for Medial Axis Transform of Plane Domain 9_bboxes](https://user-images.githubusercontent.com/38405645/67163601-c6dc8580-f368-11e9-9873-36d283811786.png)

**Comment by EliotJones** [comment]
I think the height issue may be the same as is observed in this document https://github.com/UglyToad/PdfPig/issues/75. It's potentially also an OCR font here hitting the same bit of code which returns a hard-coded bounding box of `0.25, 0` glyph dimensions (that then get transformed by `ContentStreamProcessor` code) resulting in all glyphs having no height.

Out of interest does shifting the bounding boxes by the x and y offset of the crop box move them to the correct location?

As mentioned in the other issue unfortunately I'm going to be away from my PC for the next 2-3 weeks so won't be able to fix this for a bit :(

**Comment by BobLd** [comment]
It works indeed when using:
x = letter.GlyphRectangle.Left - page.CropBox.Bounds.Left
y = letter.GlyphRectangle.Top - page.CropBox.Bounds.Bottom

see below:
![New Algorithm for Medial Axis Transform of Plane Domain 9_bboxes](https://user-images.githubusercontent.com/38405645/67165118-1fb41a00-f379-11e9-8456-eaaadfcbd5c9.png)

**Comment by EliotJones** [comment]
Hi, I've pushed up a change which seems to fix this issue for page 1 of this document but I'm being lazy and haven't checked the other pages. Please let me know if it works ok for the rest of the document.

**Comment by BobLd** [comment]
Hi, I've checked and the bounding boxes are correct for all pages.

As you said, it does not fix the cropbox issue. What do you think of making `CropBox`'s access public?

**Comment by EliotJones** [comment]
Thanks for checking.

Good point! I hadn't realised it wasn't public 🤦‍♂

**Comment by BobLd** [comment]
That's great, thanks!
